import { FilterItem } from '$lib/models/Filter';

function getCountries(): FilterItem[] {
   let countries: FilterItem[] = [];
   countries.push(new FilterItem('AF', 'Afghanistan'));
   countries.push(new FilterItem('AX', 'Åland Islands'));
   countries.push(new FilterItem('AL', 'Albania'));
   countries.push(new FilterItem('DZ', 'Algeria'));
   countries.push(new FilterItem('AS', 'American Samoa'));
   countries.push(new FilterItem('AD', 'Andorra'));
   countries.push(new FilterItem('AO', 'Angola'));
   countries.push(new FilterItem('AI', 'Anguilla'));
   countries.push(new FilterItem('AQ', 'Antarctica'));
   countries.push(new FilterItem('AG', 'Antigua and Barbuda'));
   countries.push(new FilterItem('AR', 'Argentina'));
   countries.push(new FilterItem('AM', 'Armenia'));
   countries.push(new FilterItem('AW', 'Aruba'));
   countries.push(new FilterItem('AU', 'Australia'));
   countries.push(new FilterItem('AT', 'Austria'));
   countries.push(new FilterItem('AZ', 'Azerbaijan'));
   countries.push(new FilterItem('BS', 'Bahamas'));
   countries.push(new FilterItem('BH', 'Bahrain'));
   countries.push(new FilterItem('BD', 'Bangladesh'));
   countries.push(new FilterItem('BB', 'Barbados'));
   countries.push(new FilterItem('BY', 'Belarus'));
   countries.push(new FilterItem('BE', 'Belgium'));
   countries.push(new FilterItem('BZ', 'Belize'));
   countries.push(new FilterItem('BJ', 'Benin'));
   countries.push(new FilterItem('BM', 'Bermuda'));
   countries.push(new FilterItem('BT', 'Bhutan'));
   countries.push(new FilterItem('BO', 'Bolivia'));
   countries.push(new FilterItem('BQ', 'Bonaire, Sint Eustatius and Saba'));
   countries.push(new FilterItem('BA', 'Bosnia and Herzegovina'));
   countries.push(new FilterItem('BW', 'Botswana'));
   countries.push(new FilterItem('BV', 'Bouvet Island'));
   countries.push(new FilterItem('BR', 'Brazil'));
   countries.push(new FilterItem('IO', 'British Indian Ocean Territory'));
   countries.push(new FilterItem('BN', 'Brunei Darussalam'));
   countries.push(new FilterItem('BG', 'Bulgaria'));
   countries.push(new FilterItem('BF', 'Burkina Faso'));
   countries.push(new FilterItem('BI', 'Burundi'));
   countries.push(new FilterItem('CV', 'Cabo Verde'));
   countries.push(new FilterItem('KH', 'Cambodia'));
   countries.push(new FilterItem('CM', 'Cameroon'));
   countries.push(new FilterItem('CA', 'Canada'));
   countries.push(new FilterItem('KY', 'Cayman Islands'));
   countries.push(new FilterItem('CF', 'Central African Republic'));
   countries.push(new FilterItem('TD', 'Chad'));
   countries.push(new FilterItem('CL', 'Chile'));
   countries.push(new FilterItem('CN', 'China'));
   countries.push(new FilterItem('CX', 'Christmas Island'));
   countries.push(new FilterItem('CC', 'Cocos (Keeling) Islands'));
   countries.push(new FilterItem('CO', 'Colombia'));
   countries.push(new FilterItem('KM', 'Comoros'));
   countries.push(new FilterItem('CG', 'Congo'));
   countries.push(new FilterItem('CD', 'Congo, Democratic Republic of the'));
   countries.push(new FilterItem('CK', 'Cook Islands'));
   countries.push(new FilterItem('CR', 'Costa Rica'));
   countries.push(new FilterItem('CI', "Côte d'Ivoire"));
   countries.push(new FilterItem('HR', 'Croatia'));
   countries.push(new FilterItem('CU', 'Cuba'));
   countries.push(new FilterItem('CW', 'Curaçao'));
   countries.push(new FilterItem('CY', 'Cyprus'));
   countries.push(new FilterItem('CZ', 'Czechia'));
   countries.push(new FilterItem('DK', 'Denmark'));
   countries.push(new FilterItem('DJ', 'Djibouti'));
   countries.push(new FilterItem('DM', 'Dominica'));
   countries.push(new FilterItem('DO', 'Dominican Republic'));
   countries.push(new FilterItem('EC', 'Ecuador'));
   countries.push(new FilterItem('EG', 'Egypt'));
   countries.push(new FilterItem('SV', 'El Salvador'));
   countries.push(new FilterItem('GQ', 'Equatorial Guinea'));
   countries.push(new FilterItem('ER', 'Eritrea'));
   countries.push(new FilterItem('EE', 'Estonia'));
   countries.push(new FilterItem('SZ', 'Eswatini'));
   countries.push(new FilterItem('ET', 'Ethiopia'));
   countries.push(new FilterItem('FK', 'Falkland Islands (Malvinas)'));
   countries.push(new FilterItem('FO', 'Faroe Islands'));
   countries.push(new FilterItem('FJ', 'Fiji'));
   countries.push(new FilterItem('FI', 'Finland'));
   countries.push(new FilterItem('FR', 'France'));
   countries.push(new FilterItem('GF', 'French Guiana'));
   countries.push(new FilterItem('PF', 'French Polynesia'));
   countries.push(new FilterItem('TF', 'French Southern Territories'));
   countries.push(new FilterItem('GA', 'Gabon'));
   countries.push(new FilterItem('GM', 'Gambia'));
   countries.push(new FilterItem('GE', 'Georgia'));
   countries.push(new FilterItem('DE', 'Germany'));
   countries.push(new FilterItem('GH', 'Ghana'));
   countries.push(new FilterItem('GI', 'Gibraltar'));
   countries.push(new FilterItem('GR', 'Greece'));
   countries.push(new FilterItem('GL', 'Greenland'));
   countries.push(new FilterItem('GD', 'Grenada'));
   countries.push(new FilterItem('GP', 'Guadeloupe'));
   countries.push(new FilterItem('GU', 'Guam'));
   countries.push(new FilterItem('GT', 'Guatemala'));
   countries.push(new FilterItem('GG', 'Guernsey'));
   countries.push(new FilterItem('GN', 'Guinea'));
   countries.push(new FilterItem('GW', 'Guinea-Bissau'));
   countries.push(new FilterItem('GY', 'Guyana'));
   countries.push(new FilterItem('HT', 'Haiti'));
   countries.push(new FilterItem('HM', 'Heard Island and McDonald Islands'));
   countries.push(new FilterItem('VA', 'Holy See'));
   countries.push(new FilterItem('HN', 'Honduras'));
   countries.push(new FilterItem('HK', 'Hong Kong'));
   countries.push(new FilterItem('HU', 'Hungary'));
   countries.push(new FilterItem('IS', 'Iceland'));
   countries.push(new FilterItem('IN', 'India'));
   countries.push(new FilterItem('ID', 'Indonesia'));
   countries.push(new FilterItem('IR', 'Iran'));
   countries.push(new FilterItem('IQ', 'Iraq'));
   countries.push(new FilterItem('IE', 'Ireland'));
   countries.push(new FilterItem('IM', 'Isle of Man'));
   countries.push(new FilterItem('IL', 'Israel'));
   countries.push(new FilterItem('IT', 'Italy'));
   countries.push(new FilterItem('JM', 'Jamaica'));
   countries.push(new FilterItem('JP', 'Japan'));
   countries.push(new FilterItem('JE', 'Jersey'));
   countries.push(new FilterItem('JO', 'Jordan'));
   countries.push(new FilterItem('KZ', 'Kazakhstan'));
   countries.push(new FilterItem('KE', 'Kenya'));
   countries.push(new FilterItem('KI', 'Kiribati'));
   countries.push(new FilterItem('KP', 'North Korea'));
   countries.push(new FilterItem('KR', 'South Korea'));
   countries.push(new FilterItem('KW', 'Kuwait'));
   countries.push(new FilterItem('KG', 'Kyrgyzstan'));
   countries.push(new FilterItem('LA', "Lao People's Democratic Republic"));
   countries.push(new FilterItem('LV', 'Latvia'));
   countries.push(new FilterItem('LB', 'Lebanon'));
   countries.push(new FilterItem('LS', 'Lesotho'));
   countries.push(new FilterItem('LR', 'Liberia'));
   countries.push(new FilterItem('LY', 'Libya'));
   countries.push(new FilterItem('LI', 'Liechtenstein'));
   countries.push(new FilterItem('LT', 'Lithuania'));
   countries.push(new FilterItem('LU', 'Luxembourg'));
   countries.push(new FilterItem('MO', 'Macao'));
   countries.push(new FilterItem('MG', 'Madagascar'));
   countries.push(new FilterItem('MW', 'Malawi'));
   countries.push(new FilterItem('MY', 'Malaysia'));
   countries.push(new FilterItem('MV', 'Maldives'));
   countries.push(new FilterItem('ML', 'Mali'));
   countries.push(new FilterItem('MT', 'Malta'));
   countries.push(new FilterItem('MH', 'Marshall Islands'));
   countries.push(new FilterItem('MQ', 'Martinique'));
   countries.push(new FilterItem('MR', 'Mauritania'));
   countries.push(new FilterItem('MU', 'Mauritius'));
   countries.push(new FilterItem('YT', 'Mayotte'));
   countries.push(new FilterItem('MX', 'Mexico'));
   countries.push(new FilterItem('FM', 'Micronesia'));
   countries.push(new FilterItem('MD', 'Moldova'));
   countries.push(new FilterItem('MC', 'Monaco'));
   countries.push(new FilterItem('MN', 'Mongolia'));
   countries.push(new FilterItem('ME', 'Montenegro'));
   countries.push(new FilterItem('MS', 'Montserrat'));
   countries.push(new FilterItem('MA', 'Morocco'));
   countries.push(new FilterItem('MZ', 'Mozambique'));
   countries.push(new FilterItem('MM', 'Myanmar'));
   countries.push(new FilterItem('NA', 'Namibia'));
   countries.push(new FilterItem('NR', 'Nauru'));
   countries.push(new FilterItem('NP', 'Nepal'));
   countries.push(new FilterItem('NL', 'Netherlands'));
   countries.push(new FilterItem('NC', 'New Caledonia'));
   countries.push(new FilterItem('NZ', 'New Zealand'));
   countries.push(new FilterItem('NI', 'Nicaragua'));
   countries.push(new FilterItem('NE', 'Niger'));
   countries.push(new FilterItem('NG', 'Nigeria'));
   countries.push(new FilterItem('NU', 'Niue'));
   countries.push(new FilterItem('NF', 'Norfolk Island'));
   countries.push(new FilterItem('MK', 'North Macedonia'));
   countries.push(new FilterItem('MP', 'Northern Mariana Islands'));
   countries.push(new FilterItem('NO', 'Norway'));
   countries.push(new FilterItem('OM', 'Oman'));
   countries.push(new FilterItem('PK', 'Pakistan'));
   countries.push(new FilterItem('PW', 'Palau'));
   countries.push(new FilterItem('PS', 'Palestine'));
   countries.push(new FilterItem('PA', 'Panama'));
   countries.push(new FilterItem('PG', 'Papua New Guinea'));
   countries.push(new FilterItem('PY', 'Paraguay'));
   countries.push(new FilterItem('PE', 'Peru'));
   countries.push(new FilterItem('PH', 'Philippines'));
   countries.push(new FilterItem('PN', 'Pitcairn'));
   countries.push(new FilterItem('PL', 'Poland'));
   countries.push(new FilterItem('PT', 'Portugal'));
   countries.push(new FilterItem('PR', 'Puerto Rico'));
   countries.push(new FilterItem('QA', 'Qatar'));
   countries.push(new FilterItem('RE', 'Réunion'));
   countries.push(new FilterItem('RO', 'Romania'));
   countries.push(new FilterItem('RU', 'Russian Federation'));
   countries.push(new FilterItem('RW', 'Rwanda'));
   countries.push(new FilterItem('BL', 'Saint Barthélemy'));
   countries.push(new FilterItem('SH', 'Saint Helena, Ascension and Tristan da Cunha'));
   countries.push(new FilterItem('KN', 'Saint Kitts and Nevis'));
   countries.push(new FilterItem('LC', 'Saint Lucia'));
   countries.push(new FilterItem('MF', 'Saint Martin'));
   countries.push(new FilterItem('PM', 'Saint Pierre and Miquelon'));
   countries.push(new FilterItem('VC', 'Saint Vincent and the Grenadines'));
   countries.push(new FilterItem('WS', 'Samoa'));
   countries.push(new FilterItem('SM', 'San Marino'));
   countries.push(new FilterItem('ST', 'Sao Tome and Principe'));
   countries.push(new FilterItem('SA', 'Saudi Arabia'));
   countries.push(new FilterItem('SN', 'Senegal'));
   countries.push(new FilterItem('RS', 'Serbia'));
   countries.push(new FilterItem('SC', 'Seychelles'));
   countries.push(new FilterItem('SL', 'Sierra Leone'));
   countries.push(new FilterItem('SG', 'Singapore'));
   countries.push(new FilterItem('SX', 'Sint Maarten'));
   countries.push(new FilterItem('SK', 'Slovakia'));
   countries.push(new FilterItem('SI', 'Slovenia'));
   countries.push(new FilterItem('SB', 'Solomon Islands'));
   countries.push(new FilterItem('SO', 'Somalia'));
   countries.push(new FilterItem('ZA', 'South Africa'));
   countries.push(new FilterItem('GS', 'South Georgia and the South Sandwich Islands'));
   countries.push(new FilterItem('SS', 'South Sudan'));
   countries.push(new FilterItem('ES', 'Spain'));
   countries.push(new FilterItem('LK', 'Sri Lanka'));
   countries.push(new FilterItem('SD', 'Sudan'));
   countries.push(new FilterItem('SR', 'Suriname'));
   countries.push(new FilterItem('SJ', 'Svalbard and Jan Mayen'));
   countries.push(new FilterItem('SE', 'Sweden'));
   countries.push(new FilterItem('CH', 'Switzerland'));
   countries.push(new FilterItem('SY', 'Syrian Arab Republic'));
   countries.push(new FilterItem('TW', 'Taiwan'));
   countries.push(new FilterItem('TJ', 'Tajikistan'));
   countries.push(new FilterItem('TZ', 'Tanzania'));
   countries.push(new FilterItem('TH', 'Thailand'));
   countries.push(new FilterItem('TL', 'Timor-Leste'));
   countries.push(new FilterItem('TG', 'Togo'));
   countries.push(new FilterItem('TK', 'Tokelau'));
   countries.push(new FilterItem('TO', 'Tonga'));
   countries.push(new FilterItem('TT', 'Trinidad and Tobago'));
   countries.push(new FilterItem('TN', 'Tunisia'));
   countries.push(new FilterItem('TR', 'Turkey'));
   countries.push(new FilterItem('TM', 'Turkmenistan'));
   countries.push(new FilterItem('TC', 'Turks and Caicos Islands'));
   countries.push(new FilterItem('TV', 'Tuvalu'));
   countries.push(new FilterItem('UG', 'Uganda'));
   countries.push(new FilterItem('UA', 'Ukraine'));
   countries.push(new FilterItem('AE', 'United Arab Emirates'));
   countries.push(new FilterItem('GB', 'United Kingdom'));
   countries.push(new FilterItem('US', 'United States of America'));
   countries.push(new FilterItem('UM', 'United States Minor Outlying Islands'));
   countries.push(new FilterItem('UY', 'Uruguay'));
   countries.push(new FilterItem('UZ', 'Uzbekistan'));
   countries.push(new FilterItem('VU', 'Vanuatu'));
   countries.push(new FilterItem('VE', 'Venezuela'));
   countries.push(new FilterItem('VN', 'Viet Nam'));
   countries.push(new FilterItem('VG', 'Virgin Islands (British)'));
   countries.push(new FilterItem('VI', 'Virgin Islands (U.S.)'));
   countries.push(new FilterItem('WF', 'Wallis and Futuna'));
   countries.push(new FilterItem('EH', 'Western Sahara'));
   countries.push(new FilterItem('YE', 'Yemen'));
   countries.push(new FilterItem('ZM', 'Zambia'));
   countries.push(new FilterItem('ZW', 'Zimbabwe'));

   return countries;
}

function getRegions(): FilterItem[] {
   let regions: FilterItem[] = [];
   regions.push(new FilterItem('NA', 'North America'));
   regions.push(new FilterItem('SA', 'South America'));
   regions.push(new FilterItem('EU', 'Europe'));
   regions.push(new FilterItem('AS', 'Asia'));
   regions.push(new FilterItem('AF', 'Africa'));
   regions.push(new FilterItem('OCE', 'Oceania'));
   return regions;
}

const countryFilter = getCountries();
const regionFilter = getRegions();

export default {
   countryFilter,
   regionFilter
};
