services:
   scoresaber-frontend:
      image: '${IMAGE_NAME}'
      container_name: scoresaber-frontend
      command: node build/index.js
      networks:
         - scoresaber-network
      ports:
         - 1000-1001:3000
      volumes:
         - type: bind
           source: '${HOST_ENV_FILE_PATH}'
           target: /usr/src/app/.env
      restart: on-failure
      build:
         context: ..
         dockerfile: docker/Dockerfile
networks:
   scoresaber-network:
      name: scoresaber-network
      driver: bridge
