services:
   frontend:
      image: '${IMAGE_NAME}'
      command: node -r dotenv/config build
      networks:
         - scoresaber-network
      ports:
         - 1000-1001:3000
      volumes:
         - type: bind
           source: '${CONFIG_FILE_FRONTEND}'
           target: /usr/src/app/.env
      restart: on-failure
      build:
         context: ..
         dockerfile: docker/Dockerfile
networks:
   scoresaber-network:
      name: scoresaber-network
      driver: bridge
