import { z } from 'zod';

const regionNames = new Intl.DisplayNames(['en'], { type: 'region' });

// iso 3166-1 alpha-2 codes
export const countryCodeSchema = z.enum([
   'AD',
   'AE',
   'AF',
   'AG',
   'AI',
   'AL',
   'AM',
   'AO',
   'AR',
   'AS',
   'AT',
   'AU',
   'AW',
   'AX',
   'AZ',
   'BA',
   'BB',
   'BD',
   'BE',
   'BF',
   'BG',
   'BH',
   'BI',
   'BJ',
   'BL',
   'BM',
   'BN',
   'BO',
   'BQ',
   'BR',
   'BS',
   'BT',
   'BW',
   'BY',
   'BZ',
   'CA',
   'CC',
   'CD',
   'CF',
   'CG',
   'CH',
   'CI',
   'CK',
   'CL',
   'CM',
   'CN',
   'CO',
   'CR',
   'CU',
   'CV',
   'CW',
   'CX',
   'CY',
   'CZ',
   'DE',
   'DJ',
   'DK',
   'DM',
   'DO',
   'DZ',
   'EC',
   'EE',
   'EG',
   'EH',
   'ER',
   'ES',
   'ET',
   'FI',
   'FJ',
   'FK',
   'FM',
   'FO',
   'FR',
   'GA',
   'GB',
   'GD',
   'GE',
   'GF',
   'GG',
   'GH',
   'GI',
   'GL',
   'GM',
   'GN',
   'GP',
   'GQ',
   'GR',
   'GT',
   'GU',
   'GW',
   'GY',
   'HK',
   'HN',
   'HR',
   'HT',
   'HU',
   'ID',
   'IE',
   'IL',
   'IM',
   'IN',
   'IO',
   'IQ',
   'IR',
   'IS',
   'IT',
   'JE',
   'JM',
   'JO',
   'JP',
   'KE',
   'KG',
   'KH',
   'KI',
   'KM',
   'KN',
   'KP',
   'KR',
   'KW',
   'KY',
   'KZ',
   'LA',
   'LB',
   'LC',
   'LI',
   'LK',
   'LR',
   'LS',
   'LT',
   'LU',
   'LV',
   'LY',
   'MA',
   'MC',
   'MD',
   'ME',
   'MF',
   'MG',
   'MH',
   'MK',
   'ML',
   'MM',
   'MN',
   'MO',
   'MP',
   'MQ',
   'MR',
   'MS',
   'MT',
   'MU',
   'MV',
   'MW',
   'MX',
   'MY',
   'MZ',
   'NA',
   'NC',
   'NE',
   'NF',
   'NG',
   'NI',
   'NL',
   'NO',
   'NP',
   'NR',
   'NU',
   'NZ',
   'OM',
   'PA',
   'PE',
   'PF',
   'PG',
   'PH',
   'PK',
   'PL',
   'PM',
   'PN',
   'PR',
   'PS',
   'PT',
   'PW',
   'PY',
   'QA',
   'RE',
   'RO',
   'RS',
   'RU',
   'RW',
   'SA',
   'SB',
   'SC',
   'SD',
   'SE',
   'SG',
   'SH',
   'SI',
   'SJ',
   'SK',
   'SL',
   'SM',
   'SN',
   'SO',
   'SR',
   'SS',
   'ST',
   'SV',
   'SX',
   'SY',
   'SZ',
   'TC',
   'TD',
   'TF',
   'TG',
   'TH',
   'TJ',
   'TK',
   'TL',
   'TM',
   'TN',
   'TO',
   'TR',
   'TT',
   'TV',
   'TW',
   'TZ',
   'UA',
   'UG',
   'UM',
   'US',
   'UY',
   'UZ',
   'VA',
   'VC',
   'VE',
   'VG',
   'VI',
   'VN',
   'VU',
   'WF',
   'WS',
   'XK',
   'YE',
   'YT',
   'ZA',
   'ZM',
   'ZW'
]);

const COUNTRY_CODES = countryCodeSchema.options;
export type CountryCode = z.infer<typeof countryCodeSchema>;

// readable country name from code
export function getCountryName(code: string) {
   if (!code) return 'Unknown';
   return regionNames.of(code.toUpperCase()) ?? code;
}

// all countries sorted by name
export function getCountryData() {
   return COUNTRY_CODES.map((code) => ({ code, name: getCountryName(code) })).sort((a, b) => a.name.localeCompare(b.name));
}

export type RegionCode = 'NA' | 'SA' | 'EU' | 'AS' | 'AF' | 'OCE';

interface Region {
   code: RegionCode;
   label: string;
   countries: string;
   legacyCountries?: string[];
}

export const REGIONS: Region[] = [
   {
      code: 'NA',
      label: 'North America',
      countries: 'AG,AI,AW,BB,BL,BM,BQ,BS,BZ,CA,CR,CU,CW,DM,DO,GD,GL,GP,GT,HN,HT,JM,KN,KY,LC,MF,MQ,MS,MX,NI,PA,PM,PR,SV,SX,TC,TT,US,VC,VG,VI',
      legacyCountries: ['US,CA,MX,GT,BZ,HN,SV,NI,CR,PA,CU,JM,HT,DO,PR,TT,BS,BB,AG,DM,GD,KN,LC,VC']
   },
   {
      code: 'SA',
      label: 'South America',
      countries: 'AR,BO,BR,CL,CO,EC,FK,GF,GY,PE,PY,SR,UY,VE',
      legacyCountries: ['BR,AR,CO,PE,VE,CL,EC,BO,PY,UY,GY,SR,GF']
   },
   {
      code: 'EU',
      label: 'Europe',
      countries:
         'AD,AL,AT,AX,BA,BE,BG,BY,CH,CY,CZ,DE,DK,EE,ES,FI,FO,FR,GB,GG,GI,GR,HR,HU,IE,IM,IS,IT,JE,LI,LT,LU,LV,MC,MD,ME,MK,MT,NL,NO,PL,PT,RO,RS,RU,SE,SI,SJ,SK,SM,UA,VA,XK',
      legacyCountries: [
         'GB,DE,FR,IT,ES,NL,BE,AT,CH,PL,SE,NO,DK,FI,IE,PT,CZ,RO,HU,GR,BG,HR,SK,SI,LT,LV,EE,LU,MT,CY,IS,AL,MK,ME,RS,BA,XK,MD,UA,BY',
         'GB,DE,FR,IT,ES,NL,BE,AT,CH,PL,SE,NO,DK,FI,IE,PT,CZ,RO,HU,GR,BG,HR,SK,SI,LT,LV,EE,LU,MT,CY,IS,AL,MK,ME,RS,BA,XK,MD,UA,BY,RU'
      ]
   },
   {
      code: 'AS',
      label: 'Asia',
      countries:
         'AE,AF,AM,AZ,BD,BH,BN,BT,CC,CN,CX,GE,HK,ID,IL,IN,IO,IQ,IR,JO,JP,KG,KH,KP,KR,KW,KZ,LA,LB,LK,MM,MN,MO,MV,MY,NP,OM,PH,PK,PS,QA,SA,SG,SY,TH,TJ,TM,TR,TW,UZ,VN,YE',
      legacyCountries: [
         'CN,JP,KR,IN,ID,TH,VN,PH,MY,SG,TW,HK,BD,PK,LK,NP,MM,KH,LA,MN,KZ,UZ,TJ,KG,TM,AZ,GE,AM',
         'CN,JP,KR,IN,ID,TH,VN,PH,MY,SG,TW,HK,BD,PK,LK,NP,MM,KH,LA,MN,KZ,UZ,TJ,KG,TM,AZ,GE,AM,IL'
      ]
   },
   {
      code: 'AF',
      label: 'Africa',
      countries:
         'AO,BF,BI,BJ,BW,CD,CF,CG,CI,CM,CV,DJ,DZ,EG,EH,ER,ET,GA,GH,GM,GN,GQ,GW,KE,KM,LR,LS,LY,MA,MG,ML,MR,MU,MW,MZ,NA,NE,NG,RE,RW,SC,SD,SH,SL,SN,SO,SS,ST,SZ,TD,TG,TN,TZ,UG,YT,ZA,ZM,ZW',
      legacyCountries: ['ZA,NG,EG,KE,GH,ET,TZ,UG,DZ,MA,TN,SN,CI,CM,AO,MZ,MG,ZW,ZM,RW,ML,BF,NE,TD,GN,BJ,TG,SL,LR,MR,SO,DJ,ER,GM,CV']
   },
   {
      code: 'OCE',
      label: 'Oceania',
      countries: 'AS,AU,CK,FJ,FM,GU,KI,MH,MP,NC,NF,NR,NU,NZ,PF,PG,PN,PW,SB,TK,TL,TO,TV,UM,VU,WF,WS',
      legacyCountries: ['AU,NZ,FJ,PG,WS,TO,VU,SB,KI,FM,MH,PW,NR,TV']
   }
];
